POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-243563"
}

###
DELETE http://localhost:3001/api/persons/5

###
GET http://localhost:3001/api/persons/